export var formats = [
	{suffix: " K"    , min: 1n ** 3n  },
	{suffix: " M"    , min: 1n ** 6n  },
	{suffix: " B"    , min: 1n ** 9n  },
	{suffix: " T"    , min: 1n ** 12n },
	{suffix: " Qd"   , min: 1n ** 15n },
	{suffix: " Qn"   , min: 1n ** 18n },
	{suffix: " Sx"   , min: 1n ** 21n },
	{suffix: " Sp"   , min: 1n ** 24n },
	{suffix: " O"    , min: 1n ** 27n },
	{suffix: " N"    , min: 1n ** 30n },
	{suffix: " D"    , min: 1n ** 33n },
	{suffix: " Ud"   , min: 1n ** 36n },
	{suffix: " Dd"   , min: 1n ** 39n },
	{suffix: " Td"   , min: 1n ** 42n },
	{suffix: " Qdd"  , min: 1n ** 45n },
	{suffix: " Qnd"  , min: 1n ** 48n },
	{suffix: " Sxd"  , min: 1n ** 51n },
	{suffix: " Spd"  , min: 1n ** 54n },
	{suffix: " Od"   , min: 1n ** 57n },
	{suffix: " Nd"   , min: 1n ** 60n },
	{suffix: " Vg"   , min: 1n ** 63n },
	{suffix: " UVg"  , min: 1n ** 66n },
	{suffix: " DVg"  , min: 1n ** 69n },
	{suffix: " TVg"  , min: 1n ** 72n },
	{suffix: " QdVg" , min: 1n ** 75n },
	{suffix: " QnVg" , min: 1n ** 78n },
	{suffix: " SxVg" , min: 1n ** 81n },
	{suffix: " SpVg" , min: 1n ** 84n },
	{suffix: " NVg"  , min: 1n ** 87n },
	{suffix: " OVg"  , min: 1n ** 90n },
	{suffix: " Tg"   , min: 1n ** 93n },
	{suffix: " UTg"  , min: 1n ** 96n },
	{suffix: " DTg"  , min: 1n ** 99n },
	{suffix: " TTg"  , min: 1n ** 102n},
	{suffix: " QdTg" , min: 1n ** 105n},
	{suffix: " QnTg" , min: 1n ** 108n},
	{suffix: " SxTg" , min: 1n ** 111n},
	{suffix: " SpTg" , min: 1n ** 114n},
	{suffix: " OTg"  , min: 1n ** 117n},
	{suffix: " NTg"  , min: 1n ** 120n},
	{suffix: " QDg"  , min: 1n ** 123n},
	{suffix: " Cn"   , min: 1n ** 303n}
]